server:
  port: 8088  #配置项目的端口号
  servlet:
    context-path: /yuanzi #在路径上加上项目名称
  #jdbc配置，springboot默认会把spring.datasource开头的信息收纳，进行DataSource对象的配置，进而进行sqlSessionFactory的配置等相关数据库连接的配置，从而省略了application.xml中的相关
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yuanzi_manhua_data?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml #扫描mybatis的mapper.xml文件
  type-aliases-package: com.manhua.yuanzi.model #起别名，指向实体类的位置，可省略写mybatis的xml中的resultType的全路径，取代<typeAlias alias="Admin" type="com.ljy.maven_github_ssm.model.Admin"/>

  #swagger 配置
  #swagger:
   # base-packge:com.manhua.yuanzi.web
   # title:demo
   # description:demodemo
   # version:1.1
   # term-of-service-url:www.baidu.com
   # contact:kilig
   # email:blog@qq.com